version: '3'

services:
  codefirst.model:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  codefirst.data:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat

